import re

def htmltags_filter(text : str) -> str: #this function removes HTML tags and html special characters from the string with r.e.

    cleantext = re.sub(re.compile('<.*?>'), ' ', text)
    cleantext = re.sub(re.compile('\u200b'), '', cleantext)
    cleantext = re.sub(re.compile('www.\w+.\w*(\.\w+)*(\/\w*\.*\w*)*|http(s)*:\/\/\w+.\w*(\.\w+)*(\/\w*\.*\w*)*'), ' ', cleantext)
    cleantext = re.sub(re.compile('&AElig;'), 'AE', cleantext)
    cleantext = re.sub(re.compile('&aelig;'), 'ae', cleantext)
    cleantext = re.sub(re.compile('&ETH;'), 'D', cleantext)
    cleantext = re.sub(re.compile('&Eta;'), 'H', cleantext)
    cleantext = re.sub(re.compile('&Eta;'), 'H', cleantext)
    cleantext = re.sub(re.compile('&Omega;'), 'Ω', cleantext)
    cleantext = re.sub(re.compile('&Upsilon;'), 'Y', cleantext)
    cleantext = re.sub(re.compile('&alpha;'), 'α', cleantext)
    cleantext = re.sub(re.compile('&amp;'), '&', cleantext)
    cleantext = re.sub(re.compile('&eth;'), 'o', cleantext)
    cleantext = re.sub(re.compile('&eta;'), 'n', cleantext)
    cleantext = re.sub(re.compile('&exist;'), '', cleantext)
    cleantext = re.sub(re.compile('&empty;'), 'O', cleantext)
    cleantext = re.sub(re.compile('&equiv;'), '', cleantext)
    cleantext = re.sub(re.compile('&iota;'), 'l', cleantext)
    cleantext = re.sub(re.compile('&image;'), '', cleantext)
    cleantext = re.sub(re.compile('&isin;'), '', cleantext)
    cleantext = re.sub(re.compile('&infin;'), '', cleantext)
    cleantext = re.sub(re.compile('&int;'), '', cleantext)
    cleantext = re.sub(re.compile('&iexcl;'), 'i', cleantext)
    cleantext = re.sub(re.compile('&iquest;'), '', cleantext)
    cleantext = re.sub(re.compile('&omega;'), '', cleantext)
    cleantext = re.sub(re.compile('&oline;'), '_', cleantext)
    cleantext = re.sub(re.compile('&or;'), '', cleantext)
    cleantext = re.sub(re.compile('&oplus;'), '', cleantext)
    cleantext = re.sub(re.compile('&otimes;'), '', cleantext)
    cleantext = re.sub(re.compile('&ordf;'), '', cleantext)
    cleantext = re.sub(re.compile('&ordm;'), '', cleantext)
    cleantext = re.sub(re.compile('&upsilon;'), 'v', cleantext)
    cleantext = re.sub(re.compile('&upsih;'), 'Y', cleantext)
    cleantext = re.sub(re.compile('&uarr;'), '', cleantext)
    cleantext = re.sub(re.compile('&uArr;'), '', cleantext)
    cleantext = re.sub(re.compile('&uml;'), '', cleantext)

    cleantext = re.sub(re.compile('&A.*?;'), 'A', cleantext)
    cleantext = re.sub(re.compile('&E.*?;'), 'E', cleantext)
    cleantext = re.sub(re.compile('&I.*?;'), 'I', cleantext)
    cleantext = re.sub(re.compile('&O.*?;'), 'O', cleantext)
    cleantext = re.sub(re.compile('&U.*?;'), 'U', cleantext)
    cleantext = re.sub(re.compile('&a.*?;'), 'a', cleantext)
    cleantext = re.sub(re.compile('&e.*?;'), 'e', cleantext)
    cleantext = re.sub(re.compile('&i.*?;'), 'i', cleantext)
    cleantext = re.sub(re.compile('&o.*?;'), 'o', cleantext)
    cleantext = re.sub(re.compile('&u.*?;'), 'u', cleantext)

    cleantext = re.sub(re.compile('&.*?;'), '', cleantext)

    return cleantext